export const AUTH_CHANGE_INPUT_FORM = 'AUTH_CHANGE_INPUT_FORM';
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR';

export const USER_REGISTER_AUTH_INFO = 'USER_REGISTER_AUTH_INFO';
export const USER_SET_ERROR = 'USER_SET_ERROR';
export const USER_CONFIRM_AUTH_CODE = 'USER_CONFIRM_AUTH_CODE';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const REGISTER_ALL_GET = 'REGISTER_ALL_GET';
export const REGISTER_CONTACT_DATA_CHANGE = 'REGISTER_CONTACT_DATA_CHANGE';
export const REGISTER_CONTACT_FIRST_NAME = 'REGISTER_CONTACT_FIRST_NAME';